### ISSUE TITLE
[Bug] Tampilan route di view role banyak yang double

### ISSUE THREAD

**Issue by nicovicz** [hscstudio/yii2-mimin#13]
tampilan pada saat assign route(permission) ke role banyak yg double dikarenakan penggunaan distinct yang tidak tepat

fix :

`$types = Route::find()->select('type')->distinct()->where(['status' => 1])->all();`
atau
`$types = Route::find()->where(['status' => 1])->groupBy('type')->all();`

**Comment by hscstudio** [comment]
merge
