### ISSUE TITLE
Failed to update user password 

### ISSUE THREAD

**Issue by ahmadfadlydziljalal** [hscstudio/yii2-mimin#17]
Dear Bang Hafid,

Saat update password user, password baru tidak bisa saat login.
User masih bias login menggunakan password lama.
Mungkin di old_password . CMIIW ...

Thanks buat mimin yang keren ini

Salam

**Comment by jordan095** [comment]
Pernah mengahadapi hal yang sama , solusi saya kondisi if ($model->validatePassword($model >new_password) di comment,

```php
if (!empty($model->new_password)) {
            //if ($model->validatePassword($model->new_password)) {
                                 $model->setPassword($model->new_password);
            //}
        }
```

**Comment by hscstudio** [comment]
solved

**Comment by alfarioekaputra** [comment]
Assalamualaikum mas Hafid,

untuk perubahan ini sepertinya belum terupdate di tag v1.1.3 saya tadi baru install mimin masih tidak bisa update password.

Terima Kasih
