### ISSUE TITLE
Wrong behavior Mimin::checkRoute

### ISSUE THREAD

**Issue by chiliman-oOo** [hscstudio/yii2-mimin#18]
Mimin::checkRoute('<controller/action>') return true if you've allowed any action for this controller or controller whose name starts with the same.
Fro example:
You have routes:
/client/*
/client/create
/client/view
/client-source/*

You allow access to /client/create and to/client-source/*, but if you check Mimin::checkRoute('/client/view') it returned true (.

I think it hppen there [https://github.com/hscstudio/yii2-mimin/blob/master/components/Mimin.php#L37](url)
Because AuthItem::find()->where('name LIKE :param')->addParams([':param' => $parent.'%'])->all() get
all where exist "/client%" -> "/client/create" and "/client-source/*"...

**Comment by hscstudio** [comment]
oke I have merge Your commit thx
