### ISSUE TITLE
mistake Class hscstudio\yii2-mimin\components\AccessControl does not exist

### ISSUE THREAD

**Issue by dyar74** [hscstudio/yii2-mimin#2]
Class hscstudio\yii2-mimin\components\AccessControl does not exist.
Yii2 2.0.6 basic. 
$config = [
...
'as access' => [
     'class' => 'hscstudio\mimin\components\AccessControl',
     'allowActions' => [
        // add wildcard allowed action here!
        'site/_',
        'debug/_',
        'mimin/*', // only in dev mode
    ],
]

**Comment by hscstudio** [comment]
In fact, You can see file AccessControl in folder hscstudio\yii2-mimin\components ?

Because in my pc, its run well, any ideas?

**Comment by dyar74** [comment]
In fact all files present. What OS you use?  And may be conflict with my other extensions? I am start with apache2 on Ubuntu server

**Comment by hscstudio** [comment]
I develop in OS Windows...  maybe You can add  \ in front of hscstudio
'class' => '\hscstudio\mimin\components\AccessControl',

**Comment by dyar74** [comment]
I am install free basic yii2 and not have this mistake
