### ISSUE TITLE
Membuat dynamic menu tiga tingkat

### ISSUE THREAD

**Issue by novra** [hscstudio/yii2-mimin#22]
Menu pada tingkat kedua dapat di filter tapi ketika menu pada tingkat ke tiga tidak hilang, hanya muncul forbidden ketika di klik.

**Comment by hscstudio** [comment]
mungkin benar.. saya sendiri memang fokus untuk 2 level menu sebab TB hanya support 2 level menu.. perlu modifikasi supaya support filtering lebih dari 2 level menu

**Comment by novra** [comment]
di component - mimin ya ? Function Filter menu .. okay. Klo supaya http://localhost/path/to/index.php?r=mimin/role dll g bisa diakses gimana ya ?
