### ISSUE TITLE
PHP Parse Error 'yii\base\ErrorException' with message 'syntax error, unexpected  ',''

### ISSUE THREAD

**Issue by adethis** [hscstudio/yii2-mimin#5]
> Yii Migration Tool (based on Yii v2.0.7-dev)
> 
> Total 1 new migration to be applied:
>        m151027_142811_create_route_table
> 
> Apply the above migration? (yes|no) [no]:yes
> **\* applying m151027_142811_create_route_table
> PHP Parse Error 'yii\base\ErrorException' with message 'syntax error, unexpected
> ',''
> 
> in C:\xampp\htdocs\cobalagi\vendor\hscstudio\yii2-mimin\migrations\old\m151027_1
> 42811_create_route_table.php:22
> 
> Stack trace:
> # 0 [internal function]: yii\base\ErrorHandler->handleFatalError()
> # 1 {main}

**Comment by hscstudio** [comment]
I have bug fix

https://github.com/hscstudio/yii2-mimin/blob/master/migrations/m151024_072453_create_route_table.php#L21
