### ISSUE TITLE
Run migrate got errors.

### ISSUE THREAD

**Issue by neatlife** [hscstudio/yii2-mimin#7]
➜  ... git:(feature-mimin-rbac) ✗ yii migrate --migrationPath=@hscstudio/mimin/migrations
Yii Migration Tool (based on Yii v2.0.6)

Total 1 new migration to be applied:
    m151024_072453_create_route_table

Apply the above migration? (yes|no) [no]:yes
**\* applying m151024_072453_create_route_table
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: yii\db\ColumnSchemaBuilder::primaryKey()'

in .../vendor/yiisoft/yii2/base/Object.php:220

Stack trace:
#0 .../vendor/hscstudio/yii2-mimin/migrations/m151024_072453_create_route_table.php(17): yii\base\Object->__call('primaryKey', Array)
#1 .../vendor/hscstudio/yii2-mimin/migrations/m151024_072453_create_route_table.php(17): yii\db\ColumnSchemaBuilder->primaryKey()
#2 .../vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(492): m151024_072453_create_route_table->up()
#3 .../vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(129): yii\console\controllers\BaseMigrateController->migrateUp('m151024_072453_...')
#4 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#5 .../vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#6 .../vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#7 .../vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('', Array)
#8 .../vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('', Array)
#9 .../vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('migrate', Array)
#10 .../vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('migrate', Array)
#11 .../vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#12 .../yii(27): yii\base\Application->run()
#13 {main}

php: 5.4.45
yii2: 2.0.6
os: mac os

**Comment by hscstudio** [comment]
I will verify it

**Comment by hscstudio** [comment]
@su-xiaolin : use old migration

**Comment by neatlife** [comment]
@hscstudio Ok, thank you.
