### ISSUE TITLE
View role permission are not same as supposed

### ISSUE THREAD

**Issue by jejehan** [hscstudio/yii2-mimin#8]
Assalamualaikum Uncle hafid,
thanks for your good work with this extention, but i found little problems with your extentions.
i have 2 role (admin and guest). but when i see view role for _guest_ the checkbox  check  same like role for _admin_. i think its because `$permission = $auth->getPermission($alias->name);` not include role filter. https://github.com/hscstudio/yii2-mimin/blob/master/views/role/view.php#L68

so i change that code like this:

```
$autItemChild = AuthItemChild::find()
                            ->where(['parent'=>$model->name,'child'=>$alias->name])
                            ->exists();
$checked = false;
if($autItemChild) $checked = true;
```

i added model for AuthItemChild.

and now, its work's as supposed, can you consider to implement it or you have better solution to solved this issue.

Thanks,
Zeihan Aulia

**Comment by hscstudio** [comment]
oke I have fixed this bug..
I prefer use this way

```
$permissions = $auth->getPermissionsByRole($model->name);   
...
...
$can = array_key_exists($alias->name,$permissions);
$checked = false;
if($can) $checked = true;
```

Please test 
Thanks @jejehan

**Comment by jejehan** [comment]
i have testing your code, it's be better.
and now it's running well. thank you for your response.
