### ISSUE TITLE
How to prevent customer access in backend app

### ISSUE THREAD

**Issue by jejehan** [hscstudio/yii2-mimin#9]
Asalamulaikum uncle hafid,

I want to ask, if i have 2 roles for admin and customer. 
Because now, customer can access but if he clicked menu customer he get forbiden page.
How i can prevent customer cannot be access backend?
if customer access backend, then redirect to page not found.

Thanks,
Zeihan Aulia

**Comment by hscstudio** [comment]
mainkan aja di menu

**Comment by jejehan** [comment]
mainkan dimenu?
maksudnya bagaimana ya?
untuk menu yang setau saya dia bisa mengelompokan saja kan?

kepikiran begini sih cuma belum berhasil.
sekarang lagi coba bikin kustom AccessControl yang di extends dari AccessControl Mimin.
jadi kalo dicek di tabel auth_assignment si item_name == 'customer', mau di redirect ke halaman notfound. kustom access controlnya dibuat khusus dibackend aja. jadi setiap user yang akses backend dia musti lewati pengecekan dulu disini. kalo rolesnya dia customer dia gak boleh akses, dan dialihkan ke halaman page notfound. itu berlaku hanya untuk customer aja, jika nanti ada roles baru misal "staff" dia masih bisa masuk backend dan menunya difilter pake filterRouteMenu.
barbar banget ya caranya. hehe

sementara bikin custom class begini isinya :( nambahin 1 field di user 

```
namespace backend\components;
use Yii;
use hscstudio\mimin\components\AccessControl;

class AccessControlCustom extends AccessControl{
    public function __construct(){
      $user = $this->getUser();
      if($user->identity->user_type==2){ // 2= customer
        header("Location: http://localhost/advanced/frontend/web/error");
        die();
      }
    }
}
```

**Comment by hscstudio** [comment]
Gunakan filterRouteMenu sehingga menu yang akan muncul hanya untuk user spesifik

``` php
use hscstudio\mimin\components\Mimin;
// list semua menu baik untuk admin, staff, guest
$items = [
    ['label' => 'Home', 'url' => ['/site/index']],
    ['label' => 'Administrator', 'url' => ['/admin/index']],
    ['label' => 'Super Dewa', 'url' => ['/dewa/index']],
];
// filter
$items = Mimin::filterRouteMenu($items);
// setelah di filter gini, misal yang login guest ya cuman liat menu Home doang..
if(count($items)>0){
    $menuItems[] = ['label' => 'Reporting', 'items' => $items];
}
```
